version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    image: takacsmark/flask-redis:1.0
    env_file: 
      - .env.txt
    ports:
      - 80:5000
    networks:
      - mynet

  redis:
    image: redis:${REDIS_VERSION}
    networks:
      - mynet
    volumes:
      - mydata:/data

networks:
  mynet:

volumes: 
  mydata: